// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/choose.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Choose service

func NewChooseEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Choose service

type ChooseService interface {
	DoChoose(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type chooseService struct {
	c    client.Client
	name string
}

func NewChooseService(name string, c client.Client) ChooseService {
	return &chooseService{
		c:    c,
		name: name,
	}
}

func (c *chooseService) DoChoose(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Choose.DoChoose", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Choose service

type ChooseHandler interface {
	DoChoose(context.Context, *Request, *Response) error
}

func RegisterChooseHandler(s server.Server, hdlr ChooseHandler, opts ...server.HandlerOption) error {
	type choose interface {
		DoChoose(ctx context.Context, in *Request, out *Response) error
	}
	type Choose struct {
		choose
	}
	h := &chooseHandler{hdlr}
	return s.Handle(s.NewHandler(&Choose{h}, opts...))
}

type chooseHandler struct {
	ChooseHandler
}

func (h *chooseHandler) DoChoose(ctx context.Context, in *Request, out *Response) error {
	return h.ChooseHandler.DoChoose(ctx, in, out)
}
