// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/order.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Order service

func NewOrderEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Order service

type OrderService interface {
	OrderList(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	OrderUser(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error)
	OrderAdd(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*Response, error)
	OrderDel(ctx context.Context, in *IdRequest, opts ...client.CallOption) (*Response, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) OrderList(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "Order.OrderList", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) OrderUser(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error) {
	req := c.c.NewRequest(c.name, "Order.OrderUser", in)
	out := new(UserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) OrderAdd(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.OrderAdd", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) OrderDel(ctx context.Context, in *IdRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Order.OrderDel", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Order service

type OrderHandler interface {
	OrderList(context.Context, *ListRequest, *ListResponse) error
	OrderUser(context.Context, *UserRequest, *UserResponse) error
	OrderAdd(context.Context, *AddRequest, *Response) error
	OrderDel(context.Context, *IdRequest, *Response) error
}

func RegisterOrderHandler(s server.Server, hdlr OrderHandler, opts ...server.HandlerOption) error {
	type order interface {
		OrderList(ctx context.Context, in *ListRequest, out *ListResponse) error
		OrderUser(ctx context.Context, in *UserRequest, out *UserResponse) error
		OrderAdd(ctx context.Context, in *AddRequest, out *Response) error
		OrderDel(ctx context.Context, in *IdRequest, out *Response) error
	}
	type Order struct {
		order
	}
	h := &orderHandler{hdlr}
	return s.Handle(s.NewHandler(&Order{h}, opts...))
}

type orderHandler struct {
	OrderHandler
}

func (h *orderHandler) OrderList(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.OrderHandler.OrderList(ctx, in, out)
}

func (h *orderHandler) OrderUser(ctx context.Context, in *UserRequest, out *UserResponse) error {
	return h.OrderHandler.OrderUser(ctx, in, out)
}

func (h *orderHandler) OrderAdd(ctx context.Context, in *AddRequest, out *Response) error {
	return h.OrderHandler.OrderAdd(ctx, in, out)
}

func (h *orderHandler) OrderDel(ctx context.Context, in *IdRequest, out *Response) error {
	return h.OrderHandler.OrderDel(ctx, in, out)
}
